### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dataf3l** [seletskiy/gifs#1]
I'd like to know which tool was used to create the animations

**Comment by seletskiy** [comment]
@dataf3l: GIFs were recorded using following shell-script: https://github.com/deadcrew/deadfiles/blob/master/bin/record-cast

Application to show keypresses is called screenkey: https://github.com/seletskiy/screenkey

**Comment by dataf3l** [comment]
Awesome! thank you for the prompt response! :)

**Comment by seletskiy** [comment]
You're welcome.
